gg:
  jte:
    development-mode: true
spring:
  application:
    name: telegram-webapp-auth
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format-sql: true

telegram:
  webapp:
    bot:
      token: ${TELEGRAM_WEBAPP_BOT_TOKEN}
    auth:
      validity-amount: 300

logging:
  level:
    org:
      hibernate:
        stat: DEBUG
